branchName: "${issue.number}"
branches:
  - label: enhancement
    name: develop
    prefix: feature/
    prTarget: develop
  - label: bug
    name: main
    prefix: hotfix/
    prTarget: main
autoCloseIssue: true
commentMessage: "Branch ${branchName} created for issue: ${issue.title}"
