version: "3"
services:
  redis:
    image: redis:alpine
    container_name: reids
    command: redis-server --port 6379
    expose: # 외부접속을 막기위해 ports가 아닌 expose로 설정
      - 6379

  my-own-secret-cafe-api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 8000:8000
    container_name: my-own-secret-cafe-api
    depends_on:
      - redis
